Merged PR 43651: fea: clang_format: add format arg in build script  to format app code using clang
Updated docker image to include clang-format-12

Check code formatting on PRs

Added a format argument to the build script to format app code

diff --git a/pipelines/build-mcu.yml b/pipelines/build-mcu.yml
--- a/pipelines/build-mcu.yml
+++ b/pipelines/build-mcu.yml
@@ -19,8 +19,44 @@ pool:
   demands: TM_CAP_YOCTO_BUILD -equals 1
 
 stages:
+  - stage: clang_format
+    displayName: Check formatting of code
+    pool:
+      name: 'Embedded'
+      demands: TM_CAP_YOCTO_BUILD -equals 1
+
+    jobs:
+      - job: Check_clang_format
+        timeoutInMinutes: 360
+        container:
+          image: tmesw.azurecr.io/mcu-builder:latest
+          endpoint: tmesw-container-registry
+
+        steps:
+        - checkout: self
+          clean: false
+          persistCredentials: true
+
+        - script: |
+            git clean -fxd mcu-project/apps mcu-project/modules
+            if [[ `git status --porcelain mcu-project/apps mcu-project/modules` ]]; then
+              git status
+              echo "##vso[task.logissue type=error]apps/ or modules/ is not clean after checkout."
+              exit 1
+            fi
+
+            if ! ./build.py --format; then
+              exit 1
+            fi
+            if [[ `git status --porcelain mcu-project/apps mcu-project/modules` ]]; then
+              echo "##vso[task.logissue type=error]C/C++ code in apps/ or modules/ is not correctly formatted. Run 'build.py --format'."
+              exit 1
+            fi
+          displayName: Check formatting of code
+
   - stage: west_init
     displayName: Initialize west
+    dependsOn: clang_format
     pool:
       name: 'Embedded'
       demands: TM_CAP_YOCTO_BUILD -equals 1
@@ -29,7 +65,7 @@ stages:
       - job: Init_Zephyr
         timeoutInMinutes: 360
         container:
-          image: mcu-builder:latest
+          image: tmesw.azurecr.io/mcu-builder:latest
           endpoint: tmesw-container-registry
 
         steps:
@@ -56,6 +92,7 @@ stages:
 
   - stage: ztest
     displayName: Unit tests
+    dependsOn: west_init
     pool:
       name: 'Embedded'
       demands: TM_CAP_YOCTO_BUILD -equals 1
@@ -82,7 +119,10 @@ stages:
                 echo "Updating Zephyr python requirements"
                 pip3 install --user -r zephyrproject/zephyr/scripts/requirements.txt
             fi
-            ./build.py --test
+
+            if ! ./build.py --test; then
+              exit 1
+            fi
 
             # Validate that all test passed by looking at the twister output file.
             # Twister is not returning any exit codes on failures, therefore we will manual scan the results.
@@ -130,7 +170,11 @@ stages:
                 echo "Updating Zephyr python requirements"
                 pip3 install --user -r zephyrproject/zephyr/scripts/requirements.txt
             fi
-            ./build.py -t io -l
+
+            if ! ./build.py -t io -l; then
+              exit 1
+            fi
+
             tar -czf "$(Build.ArtifactStagingDirectory)/io_bootloader_$(Build.BuildNumber).tar.gz" -C build/io/bootloader .
           displayName: Build IO bootloader
 
@@ -164,10 +208,12 @@ stages:
                 pip3 install --user -r zephyrproject/zephyr/scripts/requirements.txt
             fi
             pip3 install --user -I protobuf==3.6.1
+
             if ! ./build.py -t io; then
               echo "Failed to build IO controller"
               exit 1
             fi
+
             cp build/io/app/zephyr/zephyr.signed.bin $(Build.ArtifactStagingDirectory)/zephyr.signed-$(version).bin
 
             mkdir -p $(Build.ArtifactStagingDirectory)/proto/inner/
